### ISSUE TITLE
Send message without hear any message?

### ISSUE THREAD

**Issue by azizkhani** [baleapp/Bot-SDK-nodejs#1]
I want send message without listen to any message . your api need start to listen to message and then when new message match with pattern then send response . I want send message without  that. in telegram api you can send message with chat id . like this 
notice can send message with bot 
```
const bot = new TelegramBot(token, {polling: true});
const chatId ;
// Matches "/echo [whatever]"
bot.onText(/\/echo (.+)/, (msg, match) => {
  // 'msg' is the received Message from Telegram
  // 'match' is the result of executing the regexp above on the text content
  // of the message

  chatId = msg.chat.id;
  const resp = match[1]; // the captured "whatever"

  // send back the matched "whatever" to the chat
  bot.sendMessage(chatId, resp);
});

//send message after get chat id
 bot.sendMessage(chatId, "test");

```

**Comment by emranbm** [comment]
Hi
As said in documentations, you may want something like this:  
```javascript
let bot = new BaleBot("Your Token");
let msg = new TextMessage("Hi, I wana talk to you!");
let receiver = new User(123 /*user id*/, "321" /*user access hash*/);
bot.send(msg, receiver);
```
Note that in **Bale**, you need both `user id` and `access hash` of the user in order to send him/her a direct message. For this, you need to save the `user` / `group` (both recognized as `peer`) before.
This may help:  
```javascript
bot.setDefaultCallback((message,responder) => {
    let user = responder.peer; // The current peer (either of type group or user)
    let userId = user.id;
    let accessHash = user.accessHash;
    // Save the user (or its id/accessHash) somewhere...
});

**Comment by azizkhani** [comment]
thanks, I created a boot module for Bale. I hope to help developers get more out of this messenger,

[bot press bale module ]https://github.com/azizkhani/botpress-bale
[bale simple bot ]https://github.com/azizkhani/botpress-bale-sample
